---
- name: system packages
  register: zypper_packages
  become_user: root
  zypper:
    name: ['gnome-tweaks', 'qemu', 'qemu-kvm', 'qemu-extra', 'virt-manager', 'virt-viewer']
    state: present
    update_cache: true
